services:
  jupyter-spark:
    build: .
    container_name: tradecorp_spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

    
    environment:
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_URL: ${AZURE_STORAGE_URL}
      AZURE_CONTAINER_RAW: ${AZURE_CONTAINER_RAW}
      AZURE_CONTAINER_CLEAN: ${AZURE_CONTAINER_CLEAN}
      
    ports:
      - "8889:8888"
      - "4040:4040"

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
