services:
  jupyter-spark:
    build: .
    image: tradecorp-data-platform:latest
    container_name: tradecorp_spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ./tests:/home/jovyan/tests

    
    environment:
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_URL: ${AZURE_STORAGE_URL}
      AZURE_CONTAINER_RAW: ${AZURE_CONTAINER_RAW}
      AZURE_CONTAINER_CLEAN: ${AZURE_CONTAINER_CLEAN}
      
    ports:
      - "8889:8888"
      - "4040:4040"

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  airflow:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    image: apache/airflow:2.8.0
    container_name: tradecorp_airflow
    environment:
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_URL: ${AZURE_STORAGE_URL}
      AZURE_CONTAINER_RAW: ${AZURE_CONTAINER_RAW}
      AZURE_CONTAINER_CLEAN: ${AZURE_CONTAINER_CLEAN}
      
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - /var/run/docker.sock:/var/run/docker.sock
      - ./env:/opt/airflow/.env

    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname Admin --role Admin --email admin@admin.com --password admin || true &&
      airflow webserver &
      airflow scheduler
      "


    

volumes:
  postgres_data:
  pgadmin_data:
